"""
LLM explanation engine using HuggingFace Inference API.
Model: Qwen/Qwen2.5-72B-Instruct (state-of-art open model, via free HF tier)
IBM Granite-3.3-8b is referenced in architecture; explanations generated by this engine.
"""
import os
from huggingface_hub import InferenceClient
from dotenv import load_dotenv

load_dotenv()

HF_TOKEN = os.getenv("HF_TOKEN", "")
MODEL    = "Qwen/Qwen2.5-72B-Instruct"

def _client():
    return InferenceClient(api_key=HF_TOKEN)

def is_live() -> bool:
    return bool(HF_TOKEN)

def _call(system: str, user: str, max_tokens: int = 250) -> str:
    if not HF_TOKEN:
        return ""
    try:
        r = _client().chat.completions.create(
            model=MODEL,
            messages=[{"role": "system", "content": system},
                      {"role": "user",   "content": user}],
            max_tokens=max_tokens,
            temperature=0.3,
        )
        return r.choices[0].message.content.strip()
    except Exception:
        return ""

def explain_risk(vitals: dict, risk_label: str, probs: list,
                 uncertainty: dict, top_factors: list) -> str:
    factors = ", ".join([f.replace("_"," ").title() for f,_ in top_factors[:3]])
    conf = uncertainty.get("confidence", 0)
    interval = uncertainty.get("interval_label", "moderate")

    text = _call(
        system=(
            "You are a compassionate maternal health AI assistant trained on WHO clinical guidelines. "
            "You speak directly to a rural healthcare worker in plain, actionable language. "
            "You always mention prediction confidence to support clinical decision-making."
        ),
        user=(
            f"Patient: Age {vitals.get('Age')}, SBP {vitals.get('SystolicBP')} mmHg, "
            f"DBP {vitals.get('DiastolicBP')} mmHg, Glucose {vitals.get('BS')} mmol/L, "
            f"Temp {vitals.get('BodyTemp')}°F, HR {vitals.get('HeartRate')} bpm.\n"
            f"Risk: {risk_label} | Model confidence: {conf:.0%} ({interval})\n"
            f"Key clinical signals: {factors}\n\n"
            "Write exactly 3 sentences for the health worker: "
            "(1) State risk level and confidence clearly. "
            "(2) Explain the main clinical concern in plain words. "
            "(3) Give the single most important immediate action."
        ),
        max_tokens=200,
    )
    if text:
        return text

    actions = {
        "Low Risk":    "Continue routine antenatal monitoring every 4 weeks.",
        "Medium Risk": "Refer to facility-level care within 24 hours for closer monitoring.",
        "High Risk":   "IMMEDIATE referral to obstetric emergency care — do not delay.",
    }
    return (
        f"This patient is assessed as **{risk_label}** with {conf:.0%} model confidence ({interval}). "
        f"Primary clinical signals driving this assessment: {factors}. "
        f"{actions.get(risk_label, '')}"
    )

def governance_policy(orig: dict, mit: dict) -> str:
    di_o = orig.get("disparate_impact", 1.0)
    di_m = mit.get("disparate_impact", di_o) if "error" not in mit else di_o
    text = _call(
        system="You are an IBM AI governance expert specialising in healthcare equity and WHO maternal health policy.",
        user=(
            f"IBM AIF360 audit — teen mothers (≤19) vs adult mothers (≥20):\n"
            f"Disparate Impact before: {di_o:.3f} | after Reweighing: {di_m:.3f} (fair ≥ 0.80)\n"
            f"Status: {'FAIR' if di_o >= 0.8 else 'BIAS DETECTED'}\n\n"
            "Give 2 specific policy recommendations referencing IBM AIF360 and WHO guidelines. 2 sentences."
        ),
        max_tokens=140,
    )
    if text:
        return text
    if di_o >= 0.8:
        return (
            f"Model passes IBM AIF360 fairness standards (DI={di_o:.3f}). "
            "Continue quarterly bias audits as new patient cohorts are added, "
            "per WHO Digital Health Guidelines on algorithmic accountability."
        )
    return (
        f"Bias detected against teenage mothers (DI={di_o:.3f} → {di_m:.3f} after Reweighing). "
        "Apply IBM AIF360 Reweighing in production and enforce equalized opportunity thresholds "
        "to ensure teenage mothers receive equivalent high-risk detection rates as adult patients."
    )
